### ISSUE TITLE
zlib.h not found.

### ISSUE THREAD

**Issue by brozmical** [patriciogonzalezvivo/ofxStreetView#3]
Can't compile example file- 
tested on OF 0.8.4 and OF 0.9.3 in vs 2012 and 2015.

error C1083: Cannot open include file: 'zlib.h': No such file or directory

**Comment by mattfelsen** [comment]
I saw this recently when looking at issue #2 –– I think the Xcode/VS project files are just out of date. If you make a new project with the projectGenerator and include `ofxStreetView` and `ofxXmlSettings` you should be up & running. Happy to merge in a PR (if @patriciogonzalezvivo doesn't mind) too!

**Comment by patriciogonzalezvivo** [comment]
Be my guess @mattfelsen. Thanks so much!

**Comment by brozmical** [comment]
Thanks @mattfelsen  but that's what i did actually,if you do a merge I could try it out

**Comment by mattfelsen** [comment]
@brozmical I just pushed some changes to the [`develop`](https://github.com/patriciogonzalezvivo/ofxStreetView/commits/develop) branch (src updated for OF 0.9, updated Xcode project file) , can you try that and see if it works for you?

**Comment by brozmical** [comment]
ah it's working now, but i had to get a new version of zlib from Nuget to compile the example on VS.

**Comment by mattfelsen** [comment]
Ok, glad it's working for you. I pushed the updates to `master` anyway so the addon should be up to date for anyone else taking a look at it. Cheers!

**Comment by brozmical** [comment]
cool, but small issue that every time I include a new addon I have to reimport zlib again.

**Comment by mattfelsen** [comment]
Are you using the projectGenerator to add new addons? If so, it regenerates your project file from scratch each time, so it will wipe out any changes like your zlib update. You could try either the Visual Studio OF plugin, or add the addons by hand 😕
